### ISSUE TITLE
Help with passing data down to child components

### ISSUE THREAD

**Issue by Darkle** [Authman2/Mosaic#18]
Hi, after reading the tutorial, I was trying to figure out how to pass data down to the child components, in the tutorial it says to add the data property as an html attribute with a string default value. I tried that but I don't seem to have gotten it working. Here's my codesandbox: https://codesandbox.io/s/agitated-archimedes-hsipi

You can see that the count is undefined in the child component.

Cheers.

**Comment by Authman2** [comment]
<img width="387" alt="Screen Shot 2019-11-26 at 10 04 36 AM" src="https://user-images.githubusercontent.com/16963923/69645486-3e6e9600-1034-11ea-979b-848217e27299.png">
That's because you did not include "count" as part of the data on the child component. That's the only way the child component will know that it should expect count as data rather than as an HTML attribute.

**Comment by Darkle** [comment]
Ok thanks. Just a follow up question, is it possible for a child component to change the state in the "app" component?
